---

  - name: Make sure that lxc-docker is *not* there. (First update the cache tho)
    become: yes
    become_method: sudo
    apt:
      pkg: lxc-docker
      state: absent
      update_cache: yes
    tags: ansible_docker

  - name: Install docker-engine
    become: yes
    become_method: sudo
    apt:
      pkg: docker-engine
      state: installed
      update_cache: true
    tags: ansible_docker

  - name: Start docker
    become: yes
    become_method: sudo
    service:
      name: docker
      state: started
    tags: docker

  - name: Add docker group
    become: yes
    become_method: sudo
    group:
      name: docker
      state: present
    tags: ansible_docker

  - name: Check if {{ ansible_docker_user }} is an actual user
    become: yes
    become_method: sudo
    getent:
      database: passwd
      key: "{{ ansible_docker_user }}"
    register: ansible_docker_result
    when: ansible_docker_user is defined
    tags: ansible_docker

  - name: Add the ansible_docker_user to the docker group
    become: yes
    become_method: sudo
    user:
      name: "{{ ansible_docker_user }}"
      groups: docker
      append: yes
    when: ansible_docker_user is defined
    tags: ansible_docker

  - name: Install docker-compose
    become: yes
    become_method: sudo
    get_url:
      url: https://github.com/docker/compose/releases/download/1.8.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: "{{ ansible_docker_paths_docker_compose }}"
      mode: 0755

