---

- name: Install Baseline
  include: docker_baseline.yml
  when: install_docker|bool

- name: Install Docker
  include: docker.yml
  when: install_docker|bool

- name: Install Docker Compose
  include: docker_compose.yml
  when: install_docker_compose|bool

- name: Install Weave
  include: weave.yml
  when: weave_install|bool